#端口号为8084
server:
  port: 8084
#提供服务的微服务名称
spring:
  application:
    #在服务中心的应用名称
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          #自动映射eureka下的服务路由
          enabled: true
          #开启服务名称小写
          lower-case-service-id: true
#禁止注册自己
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka.center9001:9001/eureka
  instance:
    #显示主机名
    instance-id: cloud-gateway
    #显示主机ip
    prefer-ip-address: false